package teams

// Adaptive Card rendering for streaming replies. Cards are plain map[string]any
// objects marshaled as the attachment content. Body text is a single wrapping
// TextBlock — Teams renders the Adaptive Card markdown subset.

const adaptiveCardContentType = "application/vnd.microsoft.card.adaptive"

// loadingCard is the "working" card shown immediately while the agent thinks.
// The text is rendered italic (markdown) and subtle/small — a quiet, grayed cue.
func loadingCard(text string) map[string]any {
	if text == "" {
		text = defaultCardWorkingText
	}
	return adaptiveCard([]map[string]any{
		{"type": "TextBlock", "text": "_" + text + "_", "wrap": true, "isSubtle": true, "size": "Small"},
	})
}

// answerCard renders the (possibly partial) answer. The "Generated by AI"
// indicator is not drawn in the body — it's the native Teams AI label, attached
// to the final message as an entity (see aiGeneratedEntity).
func answerCard(markdown string) map[string]any {
	return adaptiveCard([]map[string]any{
		{"type": "TextBlock", "text": markdown, "wrap": true},
	})
}

// aiGeneratedEntity is the message entity that turns on Teams' native "AI
// generated" label (rendered next to the bot name, with the standard
// "AI-generated content may be incorrect" disclaimer). Attach it to the final
// reply's Entities. Works in personal chats, group chats, and channels.
func aiGeneratedEntity() map[string]any {
	return map[string]any{
		"type":           "https://schema.org/Message",
		"@type":          "Message",
		"@context":       "https://schema.org",
		"additionalType": []string{"AIGeneratedContent"},
	}
}

func adaptiveCard(body []map[string]any) map[string]any {
	return map[string]any{
		"type":    "AdaptiveCard",
		"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
		"version": "1.5",
		"body":    body,
	}
}

// cardActivity wraps a card object as a message activity with an Adaptive Card
// attachment, carrying the conversation-reference envelope.
func cardActivity(rc replyContext, card map[string]any) outboundActivity {
	a := newActivity(rc, "message")
	a.Attachments = []attachment{{ContentType: adaptiveCardContentType, Content: card}}
	return a
}

// aiCardActivity is cardActivity plus the native "AI generated" label entity.
// Used for every card edit (loading, streaming, final) so the label is present
// from the first render rather than appearing only at the end.
func aiCardActivity(rc replyContext, card map[string]any) outboundActivity {
	a := cardActivity(rc, card)
	a.Entities = []map[string]any{aiGeneratedEntity()}
	return a
}
