package teams

import (
	"context"
	"testing"
	"time"
)

func cardCtx() replyContext {
	return replyContext{serviceURL: "https://s/", conversationID: "c1"}
}

func TestCreateStreamingCard_InvalidContextReturnsError(t *testing.T) {
	fs := &fakeSender{id: "m1"}
	p := &Platform{conn: fs, cfg: config{}}
	// Missing serviceURL/conversationID -> engine treats the error as "no stream"
	// and falls back to a plain reply. Nothing is posted.
	card, err := p.CreateStreamingCard(context.Background(), replyContext{})
	if err == nil || card != nil {
		t.Fatalf("invalid reply context must return (nil, error), got (%v, %v)", card, err)
	}
	if fs.last.Type != "" {
		t.Error("invalid context must post nothing")
	}
}

func TestCreateStreamingCard_PostsLoadingCard(t *testing.T) {
	fs := &fakeSender{id: "m1"}
	p := &Platform{conn: fs, cfg: config{}}
	card, err := p.CreateStreamingCard(context.Background(), cardCtx())
	if err != nil || card == nil {
		t.Fatalf("card mode should create a card, got (%v, %v)", card, err)
	}
	if len(fs.last.Attachments) != 1 || fs.last.Attachments[0].ContentType != adaptiveCardContentType {
		t.Fatalf("loading card not posted as an adaptive-card attachment: %+v", fs.last)
	}
	if len(fs.last.Entities) != 1 {
		t.Errorf("loading card should carry the AI label entity from the start, got %+v", fs.last.Entities)
	}
}

func TestCreateStreamingCard_ChannelContextPostsCard(t *testing.T) {
	fs := &fakeSender{id: "m1"}
	p := &Platform{conn: fs, cfg: config{}}
	// A channel reply-thread conversation id must stream identically to 1:1.
	rc := replyContext{serviceURL: "https://s/", conversationID: "19:abc@thread.tacv2;messageid=1"}
	card, err := p.CreateStreamingCard(context.Background(), rc)
	if err != nil || card == nil {
		t.Fatalf("channel context should create a card stream, got (%v, %v)", card, err)
	}
	if _, ok := card.(*teamsStreamingCard); !ok {
		t.Fatalf("want *teamsStreamingCard, got %T", card)
	}
	if len(fs.last.Attachments) != 1 || fs.last.Attachments[0].ContentType != adaptiveCardContentType {
		t.Fatalf("channel card should post a loading adaptive card, got %+v", fs.last)
	}
}

func TestCreateStreamingCard_UsesConfiguredInterval(t *testing.T) {
	fs := &fakeSender{id: "m1"}
	p := &Platform{conn: fs, cfg: config{cardUpdateIntervalMS: 900}}
	card, err := p.CreateStreamingCard(context.Background(), cardCtx())
	if err != nil {
		t.Fatalf("CreateStreamingCard: %v", err)
	}
	tc, ok := card.(*teamsStreamingCard)
	if !ok {
		t.Fatalf("unexpected card type %T", card)
	}
	if tc.interval != 900*time.Millisecond {
		t.Errorf("interval = %v, want 900ms", tc.interval)
	}
}

func TestCreateStreamingCard_DefaultIntervalWhenUnset(t *testing.T) {
	fs := &fakeSender{id: "m1"}
	p := &Platform{conn: fs, cfg: config{}} // cardUpdateIntervalMS == 0
	card, _ := p.CreateStreamingCard(context.Background(), cardCtx())
	tc := card.(*teamsStreamingCard)
	if tc.interval != defaultCardUpdateIntervalMS*time.Millisecond {
		t.Errorf("interval = %v, want default %dms", tc.interval, defaultCardUpdateIntervalMS)
	}
}

func TestStreamingCard_UpdateEditsInPlace(t *testing.T) {
	fs := &fakeSender{}
	c := &teamsStreamingCard{conn: fs, rc: cardCtx(), activityID: "m1", interval: 0}
	if err := c.Update(context.Background(), "hello"); err != nil {
		t.Fatalf("Update: %v", err)
	}
	if len(fs.updatedIDs) != 1 || fs.updatedIDs[0] != "m1" {
		t.Fatalf("expected one in-place edit of m1, got %v", fs.updatedIDs)
	}
	if len(fs.updates[0].Attachments) != 1 {
		t.Errorf("update should carry the card attachment: %+v", fs.updates[0])
	}
	if len(fs.updates[0].Entities) != 1 {
		t.Errorf("streaming update should also carry the AI label entity, got %+v", fs.updates[0].Entities)
	}
}

func TestStreamingCard_UpdateThrottles(t *testing.T) {
	fs := &fakeSender{}
	c := &teamsStreamingCard{conn: fs, rc: cardCtx(), activityID: "m1", interval: time.Hour}
	_ = c.Update(context.Background(), "one")   // first edit bypasses throttle
	_ = c.Update(context.Background(), "two")   // within interval -> skipped
	_ = c.Update(context.Background(), "three") // skipped
	if len(fs.updates) != 1 {
		t.Errorf("throttle should coalesce to 1 edit, got %d", len(fs.updates))
	}
}

func TestStreamingCard_FinalizeAttachesAILabel(t *testing.T) {
	fs := &fakeSender{}
	c := &teamsStreamingCard{conn: fs, rc: cardCtx(), activityID: "m1", interval: time.Hour}
	if err := c.Finalize(context.Background(), "the answer"); err != nil {
		t.Fatalf("Finalize: %v", err)
	}
	if len(fs.updates) == 0 {
		t.Fatal("no final update sent")
	}
	last := fs.updates[len(fs.updates)-1]

	// Body is a single text block — no "Generated by AI" footer in the card body.
	card, _ := last.Attachments[0].Content.(map[string]any)
	if body, _ := card["body"].([]map[string]any); len(body) != 1 {
		t.Errorf("final card body should be one block (no footer), got %d", len(body))
	}
	// The native AI label rides on the message as an entity.
	if len(last.Entities) != 1 || last.Entities[0]["additionalType"] == nil {
		t.Errorf("final message should carry the AIGeneratedContent entity, got %+v", last.Entities)
	}
}

func TestStreamingCard_FinalizeFailureMarksFailed(t *testing.T) {
	fs := &fakeSender{err: context.DeadlineExceeded}
	c := &teamsStreamingCard{conn: fs, rc: cardCtx(), activityID: "m1", interval: time.Hour}
	if err := c.Finalize(context.Background(), "x"); err == nil {
		t.Fatal("expected Finalize to return the edit error")
	}
	if !c.Failed() {
		t.Error("Finalize failure should mark the card Failed (engine falls back)")
	}
}

func TestStreamingCard_UpdateErrorIsNonFatal(t *testing.T) {
	fs := &fakeSender{err: context.DeadlineExceeded}
	c := &teamsStreamingCard{conn: fs, rc: cardCtx(), activityID: "m1", interval: 0}
	if err := c.Update(context.Background(), "x"); err != nil {
		t.Errorf("Update must be best-effort, got %v", err)
	}
	if c.Failed() {
		t.Error("a mid-stream update error must not mark the card failed")
	}
}
